# Source
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=postgres
debezium.source.database.dbname=postgres
debezium.source.database.port=5432
debezium.source.database.user=postgres
debezium.source.database.password=postgres

# debezium.source.database.include.list=public
debezium.source.table.include.list=public.film,public.actor,public.customer,public.rental,public.payment
debezium.source.topic.prefix=sakila
debezium.source.plugin.name=pgoutput

# Offset configuration
debezium.source.offset.storage=io.debezium.storage.redis.offset.RedisOffsetBackingStore
debezium.source.offset.storage.redis.address=redis:6379
# debezium.source.offset.storage.redis.password=myredispw
debezium.source.offset.storage.redis.key=metadata:debezium:offsets
debezium.source.offset.storage.redis.wait.enabled=false
debezium.source.offset.storage.redis.wait.retry.enabled=true
debezium.source.offset.storage.redis.wait.retry.delay.ms=5000

# Schema history
debezium.source.schema.history.internal=io.debezium.storage.redis.history.RedisSchemaHistory
# debezium.source.schema.history.internal.redis.address=redis:6379
# debezium.source.schema.history.internal.redis.password=myredispw
debezium.source.schema.history.internal.redis.key=metadata:debezium:schema_history
debezium.source.schema.history.internal.redis.wait.enabled=false
debezium.source.schema.history.internal.redis.wait.retry.enabled=true
debezium.source.schema.history.internal.redis.wait.retry.delay.ms=5000

# Sink
debezium.sink.type=redis
debezium.sink.redis.address=redis:6379

# Logging
quarkus.log.console.json=false