spring.kafka.streams.bootstrap-servers=localhost:9095
spring.kafka.streams.group-id=sb-kfk-str-csm-catalog
spring.kafka.streams.autoOffsetReset=earliest
spring.kafka.streams.auto-startup=false

spring.kafka.topic.film=public.film
spring.kafka.topic.actor=public.actor
spring.kafka.topic.category=public.category
spring.kafka.topic.film.actor=public.film.actor
spring.kafka.topic.film.category=public.film.category

#server.port=8081
#spring.kafka.bootstrap-server=localhost:9095
#spring.kafka.topic.demo=demo-topic
#spring.kafka.topic.texassales=demo-texas-toyota-sales
#spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false