services:
  minio:
    container_name: minio
    hostname: minio
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - ./minio-data:/data
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      - sakila_net

networks:
  sakila_net:
    name: sakila_net
    external: true
