services:
  valkye:
    image: valkey/valkey-extensions:8
    deploy:
      resources:
        limits:
          #          cpus: "1"
          memory: 3G
    container_name: valkye-server
    hostname: valkye-server
    restart: always
    command: "valkey-server /usr/local/etc/valkey/valkey.conf"
    volumes:
      - ./vlk_data:/data":rw
      - ./config:/usr/local/etc/valkey:ro
    ports:
      - "6379:6379"

    networks:
      - sakila_net

  #  redisinsight:
  #    container_name: redisinsight
  #    hostname: redisinsight
  #    image: redis/redisinsight:latest
  #    restart: always
  #    environment:
  #      - REDIS_HOSTS=valkye-server
  #    ports:
  #      - "5540:5540"
  #    networks:
  #      - sakila_net

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=dev:valkye-server:6379
    ports:
      - "8081:8081"
    networks:
      - sakila_net

networks:
  sakila_net:
    name: sakila_net
    external: true
